package enums;
import model.Card;

import java.net.URL;

public enum Path {
    Monsters_arachas(CardInfo.Arachas, Card.class.getResource("/gwentImages/img/lg/monsters_arachas.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_arachas.jpg")),
    Monsters_arachas_1(CardInfo.Arachas,Card.class.getResource("/gwentImages/img/lg/monsters_arachas_1.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_arachas_1.jpg")),
    Monsters_arachas_2(CardInfo.Arachas,Card.class.getResource("/gwentImages/img/lg/monsters_arachas_2.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_arachas_2.jpg")),
    Monsters_arachas_behemoth(CardInfo.ArachasBehemoth,Card.class.getResource("/gwentImages/img/lg/monsters_arachas_behemoth.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_arachas_behemoth.jpg")),
    Monsters_bruxa(CardInfo.VampireBruxa,Card.class.getResource("/gwentImages/img/lg/monsters_bruxa.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_bruxa.jpg")),
    Monsters_celaeno_harpy(CardInfo.CelaenoHarpy,Card.class.getResource("/gwentImages/img/lg/monsters_celaeno_harpy.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_celaeno_harpy.jpg")),
    Monsters_cockatrice(CardInfo.Cockatrice,Card.class.getResource("/gwentImages/img/lg/monsters_cockatrice.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_cockatrice.jpg")),
    Monsters_draug(CardInfo.Draug,Card.class.getResource("/gwentImages/img/lg/monsters_draug.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_draug.jpg")),
    Monsters_earth_elemental(CardInfo.EarthElemental,Card.class.getResource("/gwentImages/img/lg/monsters_earth_elemental.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_earth_elemental.jpg")),
    Monsters_ekkima(CardInfo.VampireEkimmara,Card.class.getResource("/gwentImages/img/lg/monsters_ekkima.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_ekkima.jpg")),
    Monsters_endrega(CardInfo.Endrega,Card.class.getResource("/gwentImages/img/lg/monsters_endrega.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_endrega.jpg")),
    Monsters_eredin_bronze(CardInfo.KingOfTheWildHunt,Card.class.getResource("/gwentImages/img/lg/monsters_eredin_bronze.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_eredin_bronze.jpg")),
    Monsters_eredin_copper(CardInfo.CommanderOfTheRedRiders,Card.class.getResource("/gwentImages/img/lg/monsters_eredin_copper.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_eredin_copper.jpg")),
    Monsters_eredin_gold(CardInfo.DestroyerOfWorlds,Card.class.getResource("/gwentImages/img/lg/monsters_eredin_gold.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_eredin_gold.jpg")),
    Monsters_eredin_silver(CardInfo.BringerOfDeath,Card.class.getResource("/gwentImages/img/lg/monsters_eredin_silver.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_eredin_silver.jpg")),
    Monsters_eredin_the_treacherous(CardInfo.TheTreacherous, Card.class.getResource("/gwentImages/img/lg/monsters_eredin_the_treacherous.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_eredin_the_treacherous.jpg")),
    Monsters_fiend(CardInfo.Fiend,Card.class.getResource("/gwentImages/img/lg/monsters_fiend.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_fiend.jpg")),
    Monsters_fire_elemental(CardInfo.FireElemental,Card.class.getResource("/gwentImages/img/lg/monsters_fire_elemental.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_fire_elemental.jpg")),
    Monsters_fleder(CardInfo.VampireFleder,Card.class.getResource("/gwentImages/img/lg/monsters_fleder.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_fleder.jpg")),
    Monsters_fogling(CardInfo.Foglet,Card.class.getResource("/gwentImages/img/lg/monsters_fogling.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_fogling.jpg")),
    Monsters_forktail(CardInfo.Forktail,Card.class.getResource("/gwentImages/img/lg/monsters_forktail.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_forktail.jpg")),
    Monsters_frightener(CardInfo.Frightener,Card.class.getResource("/gwentImages/img/lg/monsters_frightener.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_frightener.jpg")),
    Monsters_frost_giant(CardInfo.IceGiant,Card.class.getResource("/gwentImages/img/lg/monsters_frost_giant.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_frost_giant.jpg")),
    Monsters_gargoyle(CardInfo.Gargoyle,Card.class.getResource("/gwentImages/img/lg/monsters_gargoyle.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_gargoyle.jpg")),
    Monsters_garkain(CardInfo.VampireGrakain,Card.class.getResource("/gwentImages/img/lg/monsters_garkain.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_garkain.jpg")),
    Monsters_ghoul(CardInfo.Ghoul,Card.class.getResource("/gwentImages/img/lg/monsters_ghoul.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_ghoul.jpg")),
    Monsters_ghoul_1(CardInfo.Ghoul,Card.class.getResource("/gwentImages/img/lg/monsters_ghoul_1.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_ghoul_1.jpg")),
    Monsters_ghoul_2(CardInfo.Ghoul,Card.class.getResource("/gwentImages/img/lg/monsters_ghoul_2.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_ghoul_2.jpg")),
    Monsters_gravehag(CardInfo.GraveHag,Card.class.getResource("/gwentImages/img/lg/monsters_gravehag.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_gravehag.jpg")),
    Monsters_gryffin(CardInfo.Griffin,Card.class.getResource("/gwentImages/img/lg/monsters_gryffin.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_gryffin.jpg")),
    Monsters_harpy(CardInfo.Harpy,Card.class.getResource("/gwentImages/img/lg/monsters_harpy.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_harpy.jpg")),
    Monsters_imlerith(CardInfo.Imlerith,Card.class.getResource("/gwentImages/img/lg/monsters_imlerith.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_imlerith.jpg")),
    Monsters_katakan(CardInfo.VampireKatakan,Card.class.getResource("/gwentImages/img/lg/monsters_katakan.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_katakan.jpg")),
    Monsters_kayran(CardInfo.Kayran,Card.class.getResource("/gwentImages/img/lg/monsters_kayran.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_kayran.jpg")),
    Monsters_leshen(CardInfo.Leshen,Card.class.getResource("/gwentImages/img/lg/monsters_leshen.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_leshen.jpg")),
    Monsters_mighty_maiden(CardInfo.PlagueMaiden,Card.class.getResource("/gwentImages/img/lg/monsters_mighty_maiden.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_mighty_maiden.jpg")),
    Monsters_nekker(CardInfo.Nekker,Card.class.getResource("/gwentImages/img/lg/monsters_nekker.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_nekker.jpg")),
    Monsters_nekker_1(CardInfo.Nekker,Card.class.getResource("/gwentImages/img/lg/monsters_nekker_1.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_nekker_1.jpg")),
    Monsters_nekker_2(CardInfo.Nekker,Card.class.getResource("/gwentImages/img/lg/monsters_nekker_2.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_nekker_2.jpg")),
    Monsters_poroniec(CardInfo.Botchling,Card.class.getResource("/gwentImages/img/lg/monsters_poroniec.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_poroniec.jpg")),
    Monsters_toad(CardInfo.Toad,Card.class.getResource("/gwentImages/img/lg/monsters_toad.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_toad.jpg")),
    Monsters_werewolf(CardInfo.Werewolf,Card.class.getResource("/gwentImages/img/lg/monsters_werewolf.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_werewolf.jpg")),
    Monsters_witch_velen(CardInfo.CroneBrewess,Card.class.getResource("/gwentImages/img/lg/monsters_witch_velen.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_witch_velen.jpg")),
    Monsters_witch_velen_1(CardInfo.CroneWeavess,Card.class.getResource("/gwentImages/img/lg/monsters_witch_velen_1.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_witch_velen_1.jpg")),
    Monsters_witch_velen_2(CardInfo.CroneWhispess,Card.class.getResource("/gwentImages/img/lg/monsters_witch_velen_2.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_witch_velen_2.jpg")),
    Monsters_wyvern(CardInfo.Wyvern,Card.class.getResource("/gwentImages/img/lg/monsters_wyvern.jpg"), Card.class.getResource("/gwentImages/img/sm/monsters_wyvern.jpg")),
    //Neutral_chort(Card.class.getResource("/gwentImages/img/lg/neutral_chort.jpg")),
    //Neutral_ciri(Card.class.getResource("/gwentImages/img/lg/neutral_ciri.jpg")),
    Neutral_cow(CardInfo.Cow,Card.class.getResource("/gwentImages/img/lg/neutral_cow.jpg"), Card.class.getResource("/gwentImages/img/sm/neutral_cow.jpg")),
    Neutral_dandelion(CardInfo.Dandelion,Card.class.getResource("/gwentImages/img/lg/neutral_dandelion.jpg"), Card.class.getResource("/gwentImages/img/sm/neutral_dandelion.jpg")),
    Neutral_emiel(CardInfo.EmielRegis,Card.class.getResource("/gwentImages/img/lg/neutral_emiel.jpg"), Card.class.getResource("/gwentImages/img/sm/neutral_emiel.jpg")),
    Neutral_gaunter_odimm(CardInfo.GaunterODimm,Card.class.getResource("/gwentImages/img/lg/neutral_gaunter_odimm.jpg"), Card.class.getResource("/gwentImages/img/sm/neutral_gaunter_odimm.jpg")),
    Neutral_gaunter_odimm_darkness(CardInfo.GaunterODImmDarkness,Card.class.getResource("/gwentImages/img/lg/neutral_gaunter_odimm_darkness.jpg"), Card.class.getResource("/gwentImages/img/sm/neutral_gaunter_odimm_darkness.jpg")),
    Neutral_geralt(CardInfo.GeraltOfRivia,Card.class.getResource("/gwentImages/img/lg/neutral_geralt.jpg"), Card.class.getResource("/gwentImages/img/sm/neutral_geralt.jpg")),
    Neutral_mysterious_elf(CardInfo.MysteriousElf,Card.class.getResource("/gwentImages/img/lg/neutral_mysterious_elf.jpg"), Card.class.getResource("/gwentImages/img/sm/neutral_mysterious_elf.jpg")),
    Neutral_olgierd(CardInfo.OlgierdVonEverc,Card.class.getResource("/gwentImages/img/lg/neutral_olgierd.jpg"), Card.class.getResource("/gwentImages/img/sm/neutral_olgierd.jpg")),
    Neutral_triss(CardInfo.TrissMerigold,Card.class.getResource("/gwentImages/img/lg/neutral_triss.jpg"), Card.class.getResource("/gwentImages/img/sm/neutral_triss.jpg")),
    Neutral_vesemir(CardInfo.Vesemir,Card.class.getResource("/gwentImages/img/lg/neutral_vesemir.jpg"), Card.class.getResource("/gwentImages/img/sm/neutral_vesemir.jpg")),
    Neutral_villen(CardInfo.Villentretenmerth,Card.class.getResource("/gwentImages/img/lg/neutral_villen.jpg"), Card.class.getResource("/gwentImages/img/sm/neutral_villen.jpg")),
    Neutral_yennefer(CardInfo.YenneferOfVengerberg,Card.class.getResource("/gwentImages/img/lg/neutral_yennefer.jpg"), Card.class.getResource("/gwentImages/img/sm/neutral_yennefer.jpg")),
    Neutral_zoltan(CardInfo.ZoltanChivay,Card.class.getResource("/gwentImages/img/lg/neutral_zoltan.jpg"), Card.class.getResource("/gwentImages/img/sm/neutral_zoltan.jpg")),
    Nilfgaard_albrich(CardInfo.Albrich,Card.class.getResource("/gwentImages/img/lg/nilfgaard_albrich.jpg"), Card.class.getResource("/gwentImages/img/sm/nilfgaard_albrich.jpg")),
    Nilfgaard_archer_support(CardInfo.EtolianAuxiliaryArchers,Card.class.getResource("/gwentImages/img/lg/nilfgaard_archer_support.jpg"), Card.class.getResource("/gwentImages/img/sm/nilfgaard_archer_support.jpg")),
    Nilfgaard_archer_support_1(CardInfo.EtolianAuxiliaryArchers,Card.class.getResource("/gwentImages/img/lg/nilfgaard_archer_support_1.jpg"), Card.class.getResource("/gwentImages/img/sm/nilfgaard_archer_support_1.jpg")),
    Nilfgaard_assire(CardInfo.AssirevarAnahid,Card.class.getResource("/gwentImages/img/lg/nilfgaard_assire.jpg"), Card.class.getResource("/gwentImages/img/sm/nilfgaard_assire.jpg")),
    Nilfgaard_black_archer(CardInfo.BlackInfantryArcher,Card.class.getResource("/gwentImages/img/lg/nilfgaard_black_archer.jpg"), Card.class.getResource("/gwentImages/img/sm/nilfgaard_black_archer.jpg")),
    Nilfgaard_black_archer_1(CardInfo.BlackInfantryArcher,Card.class.getResource("/gwentImages/img/lg/nilfgaard_black_archer_1.jpg"), Card.class.getResource("/gwentImages/img/sm/nilfgaard_black_archer_1.jpg")),
    Nilfgaard_cahir(CardInfo.CahirMawrDyffrynaepCeallach,Card.class.getResource("/gwentImages/img/lg/nilfgaard_cahir.jpg"), Card.class.getResource("/gwentImages/img/sm/nilfgaard_cahir.jpg")),
    Nilfgaard_cynthia(CardInfo.Cynthia,Card.class.getResource("/gwentImages/img/lg/nilfgaard_cynthia.jpg"), Card.class.getResource("/gwentImages/img/sm/nilfgaard_cynthia.jpg")),
    Nilfgaard_emhyr_bronze(CardInfo.EmperorOfNilfgaard,Card.class.getResource("/gwentImages/img/lg/nilfgaard_emhyr_bronze.jpg"), Card.class.getResource("/gwentImages/img/sm/nilfgaard_emhyr_bronze.jpg")),
    Nilfgaard_emhyr_copper(CardInfo.HisImperialMajesty,Card.class.getResource("/gwentImages/img/lg/nilfgaard_emhyr_copper.jpg"), Card.class.getResource("/gwentImages/img/sm/nilfgaard_emhyr_copper.jpg")),
    Nilfgaard_emhyr_gold(CardInfo.TheRelentless,Card.class.getResource("/gwentImages/img/lg/nilfgaard_emhyr_gold.jpg"), Card.class.getResource("/gwentImages/img/sm/nilfgaard_emhyr_gold.jpg")),
    Nilfgaard_emhyr_invader_of_the_north(CardInfo.InvaderOfTheNorth,Card.class.getResource("/gwentImages/img/lg/nilfgaard_emhyr_invader_of_the_north.jpg"), Card.class.getResource("/gwentImages/img/sm/nilfgaard_emhyr_invader_of_the_north.jpg")),
    Nilfgaard_emhyr_silver(CardInfo.TheWhiteFlame,Card.class.getResource("/gwentImages/img/lg/nilfgaard_emhyr_silver.jpg"), Card.class.getResource("/gwentImages/img/sm/nilfgaard_emhyr_silver.jpg")),
    Nilfgaard_fringilla(CardInfo.FringillaVigo,Card.class.getResource("/gwentImages/img/lg/nilfgaard_fringilla.jpg"), Card.class.getResource("/gwentImages/img/sm/nilfgaard_fringilla.jpg")),
    Nilfgaard_heavy_zerri(CardInfo.HeavyZerrikanianFireScorpion,Card.class.getResource("/gwentImages/img/lg/nilfgaard_heavy_zerri.jpg"), Card.class.getResource("/gwentImages/img/sm/nilfgaard_heavy_zerri.jpg")),
    Nilfgaard_imperal_brigade(CardInfo.ImperaBrigadeGuard,Card.class.getResource("/gwentImages/img/lg/nilfgaard_imperal_brigade.jpg"), Card.class.getResource("/gwentImages/img/sm/nilfgaard_imperal_brigade.jpg")),
    Nilfgaard_letho(CardInfo.LethoofGulet,Card.class.getResource("/gwentImages/img/lg/nilfgaard_letho.jpg"), Card.class.getResource("/gwentImages/img/sm/nilfgaard_letho.jpg")),
    Nilfgaard_menno(CardInfo.MennoCoehoorn,Card.class.getResource("/gwentImages/img/lg/nilfgaard_menno.jpg"), Card.class.getResource("/gwentImages/img/sm/nilfgaard_menno.jpg")),
    Nilfgaard_moorvran(CardInfo.MorvranVoorhis,Card.class.getResource("/gwentImages/img/lg/nilfgaard_moorvran.jpg"), Card.class.getResource("/gwentImages/img/sm/nilfgaard_moorvran.jpg")),
    Nilfgaard_morteisen(CardInfo.Morteisen,Card.class.getResource("/gwentImages/img/lg/nilfgaard_morteisen.jpg"), Card.class.getResource("/gwentImages/img/sm/nilfgaard_morteisen.jpg")),
    Nilfgaard_nauzicaa_2(CardInfo.NausicaaCavalryRider,Card.class.getResource("/gwentImages/img/lg/nilfgaard_nauzicaa_2.jpg"), Card.class.getResource("/gwentImages/img/sm/nilfgaard_nauzicaa_2.jpg")),
    Nilfgaard_puttkammer(CardInfo.Puttkammer,Card.class.getResource("/gwentImages/img/lg/nilfgaard_puttkammer.jpg"), Card.class.getResource("/gwentImages/img/sm/nilfgaard_puttkammer.jpg")),
    Nilfgaard_rainfarn(CardInfo.Rainfarn,Card.class.getResource("/gwentImages/img/lg/nilfgaard_rainfarn.jpg"), Card.class.getResource("/gwentImages/img/sm/nilfgaard_rainfarn.jpg")),
    Nilfgaard_renuald(CardInfo.RenualdaepMatsen,Card.class.getResource("/gwentImages/img/lg/nilfgaard_renuald.jpg"), Card.class.getResource("/gwentImages/img/sm/nilfgaard_renuald.jpg")),
    Nilfgaard_rotten(CardInfo.RottenMangonel,Card.class.getResource("/gwentImages/img/lg/nilfgaard_rotten.jpg"), Card.class.getResource("/gwentImages/img/sm/nilfgaard_rotten.jpg")),
    Nilfgaard_shilard(CardInfo.ShilardFitzOesterlen,Card.class.getResource("/gwentImages/img/lg/nilfgaard_shilard.jpg"), Card.class.getResource("/gwentImages/img/sm/nilfgaard_shilard.jpg")),
    Nilfgaard_siege_engineer(CardInfo.SiegeEngineer,Card.class.getResource("/gwentImages/img/lg/nilfgaard_siege_engineer.jpg"), Card.class.getResource("/gwentImages/img/sm/nilfgaard_siege_engineer.jpg")),
    Nilfgaard_siege_support(CardInfo.SiegeTechnician,Card.class.getResource("/gwentImages/img/lg/nilfgaard_siege_support.jpg"), Card.class.getResource("/gwentImages/img/sm/nilfgaard_siege_support.jpg")),
    Nilfgaard_stefan(CardInfo.StefanSkellen,Card.class.getResource("/gwentImages/img/lg/nilfgaard_stefan.jpg"), Card.class.getResource("/gwentImages/img/sm/nilfgaard_stefan.jpg")),
    Nilfgaard_sweers(CardInfo.Sweers,Card.class.getResource("/gwentImages/img/lg/nilfgaard_sweers.jpg"), Card.class.getResource("/gwentImages/img/sm/nilfgaard_sweers.jpg")),
    Nilfgaard_tibor(CardInfo.TiborEggebracht,Card.class.getResource("/gwentImages/img/lg/nilfgaard_tibor.jpg"), Card.class.getResource("/gwentImages/img/sm/nilfgaard_tibor.jpg")),
    Nilfgaard_vanhemar(CardInfo.Vanhemar,Card.class.getResource("/gwentImages/img/lg/nilfgaard_vanhemar.jpg"), Card.class.getResource("/gwentImages/img/sm/nilfgaard_vanhemar.jpg")),
    Nilfgaard_vattier(CardInfo.VattierDeRideaux,Card.class.getResource("/gwentImages/img/lg/nilfgaard_vattier.jpg"), Card.class.getResource("/gwentImages/img/sm/nilfgaard_vattier.jpg")),
    Nilfgaard_vreemde(CardInfo.Vreemde,Card.class.getResource("/gwentImages/img/lg/nilfgaard_vreemde.jpg"), Card.class.getResource("/gwentImages/img/sm/nilfgaard_vreemde.jpg")),
    Nilfgaard_young_emissary(CardInfo.YoungEmissary,Card.class.getResource("/gwentImages/img/lg/nilfgaard_young_emissary.jpg"), Card.class.getResource("/gwentImages/img/sm/nilfgaard_young_emissary.jpg")),
    Nilfgaard_young_emissary_1(CardInfo.YoungEmissary,Card.class.getResource("/gwentImages/img/lg/nilfgaard_young_emissary_1.jpg"), Card.class.getResource("/gwentImages/img/sm/nilfgaard_young_emissary_1.jpg")),
    Nilfgaard_zerri(CardInfo.ZerrikanianFirScorpion,Card.class.getResource("/gwentImages/img/lg/nilfgaard_zerri.jpg"), Card.class.getResource("/gwentImages/img/sm/nilfgaard_zerri.jpg")),
    Realms_ballista(CardInfo.Ballista,Card.class.getResource("/gwentImages/img/lg/realms_ballista.jpg"), Card.class.getResource("/gwentImages/img/sm/realms_ballista.jpg")),
    Realms_banner_nurse(CardInfo.DunBannerMedic,Card.class.getResource("/gwentImages/img/lg/realms_banner_nurse.jpg"), Card.class.getResource("/gwentImages/img/sm/realms_banner_nurse.jpg")),
    Realms_blue_stripes(CardInfo.BlueStripesCommando,Card.class.getResource("/gwentImages/img/lg/realms_blue_stripes.jpg"), Card.class.getResource("/gwentImages/img/sm/realms_blue_stripes.jpg")),
    Realms_catapult_1(CardInfo.Catapult,Card.class.getResource("/gwentImages/img/lg/realms_catapult_1.jpg"), Card.class.getResource("/gwentImages/img/sm/realms_catapult_1.jpg")),
    Realms_crinfrid(CardInfo.DragonHunter,Card.class.getResource("/gwentImages/img/lg/realms_crinfrid.jpg"), Card.class.getResource("/gwentImages/img/sm/realms_crinfrid.jpg")),
    Realms_dethmold(CardInfo.Dethmold,Card.class.getResource("/gwentImages/img/lg/realms_dethmold.jpg"), Card.class.getResource("/gwentImages/img/sm/realms_dethmold.jpg")),
    Realms_dijkstra(CardInfo.SigismundDijkstra,Card.class.getResource("/gwentImages/img/lg/realms_dijkstra.jpg"), Card.class.getResource("/gwentImages/img/sm/realms_dijkstra.jpg")),
    Realms_esterad(CardInfo.EsteradThyssen,Card.class.getResource("/gwentImages/img/lg/realms_esterad.jpg"), Card.class.getResource("/gwentImages/img/sm/realms_esterad.jpg")),
    Realms_foltest_bronze(CardInfo.LordCommanderOfTheNorth,Card.class.getResource("/gwentImages/img/lg/realms_foltest_bronze.jpg"), Card.class.getResource("/gwentImages/img/sm/realms_foltest_bronze.jpg")),
    Realms_foltest_copper(CardInfo.KingOfTemeria,Card.class.getResource("/gwentImages/img/lg/realms_foltest_copper.jpg"), Card.class.getResource("/gwentImages/img/sm/realms_foltest_copper.jpg")),
    Realms_foltest_gold(CardInfo.TheSteelForged,Card.class.getResource("/gwentImages/img/lg/realms_foltest_gold.jpg"), Card.class.getResource("/gwentImages/img/sm/realms_foltest_gold.jpg")),
    Realms_foltest_silver(CardInfo.TheSiegmaster,Card.class.getResource("/gwentImages/img/lg/realms_foltest_silver.jpg"), Card.class.getResource("/gwentImages/img/sm/realms_foltest_silver.jpg")),
    Realms_foltest_son_of_medell(CardInfo.SonOfMedell,Card.class.getResource("/gwentImages/img/lg/realms_foltest_son_of_medell.jpg"), Card.class.getResource("/gwentImages/img/sm/realms_foltest_son_of_medell.jpg")),
    Realms_kaedwen_siege(CardInfo.KaedweniSiegeExpert,Card.class.getResource("/gwentImages/img/lg/realms_kaedwen_siege.jpg"), Card.class.getResource("/gwentImages/img/sm/realms_kaedwen_siege.jpg")),
    Realms_kaedwen_siege_1(CardInfo.KaedweniSiegeExpert,Card.class.getResource("/gwentImages/img/lg/realms_kaedwen_siege_1.jpg"), Card.class.getResource("/gwentImages/img/sm/realms_kaedwen_siege_1.jpg")),
    Realms_kaedwen_siege_2(CardInfo.KaedweniSiegeExpert,Card.class.getResource("/gwentImages/img/lg/realms_kaedwen_siege_2.jpg"), Card.class.getResource("/gwentImages/img/sm/realms_kaedwen_siege_2.jpg")),
    Realms_keira(CardInfo.KeiraMetz,Card.class.getResource("/gwentImages/img/lg/realms_keira.jpg"), Card.class.getResource("/gwentImages/img/sm/realms_keira.jpg")),
    Realms_natalis(CardInfo.JohnNatalis,Card.class.getResource("/gwentImages/img/lg/realms_natalis.jpg"), Card.class.getResource("/gwentImages/img/sm/realms_natalis.jpg")),
    Realms_philippa(CardInfo.PhilippaEilhart,Card.class.getResource("/gwentImages/img/lg/realms_philippa.jpg"), Card.class.getResource("/gwentImages/img/sm/realms_philippa.jpg")),
    Realms_poor_infantry(CardInfo.PoorFuckingInfantry,Card.class.getResource("/gwentImages/img/lg/realms_poor_infantry.jpg"), Card.class.getResource("/gwentImages/img/sm/realms_poor_infantry.jpg")),
    Realms_redania(CardInfo.RedanianFootSoldier,Card.class.getResource("/gwentImages/img/lg/realms_redania.jpg"), Card.class.getResource("/gwentImages/img/sm/realms_redania.jpg")),
    Realms_redania_1(CardInfo.RedanianFootSoldier,Card.class.getResource("/gwentImages/img/lg/realms_redania_1.jpg"), Card.class.getResource("/gwentImages/img/sm/realms_redania_1.jpg")),
    Realms_sabrina(CardInfo.SabrinaGlevissing,Card.class.getResource("/gwentImages/img/lg/realms_sabrina.jpg"), Card.class.getResource("/gwentImages/img/sm/realms_sabrina.jpg")),
    Realms_sheala(CardInfo.SíledeTansarville,Card.class.getResource("/gwentImages/img/lg/realms_sheala.jpg"), Card.class.getResource("/gwentImages/img/sm/realms_sheala.jpg")),
    Realms_sheldon(CardInfo.SheldonSkaggs,Card.class.getResource("/gwentImages/img/lg/realms_sheldon.jpg"), Card.class.getResource("/gwentImages/img/sm/realms_sheldon.jpg")),
    Realms_siege_tower(CardInfo.SiegeTower,Card.class.getResource("/gwentImages/img/lg/realms_siege_tower.jpg"), Card.class.getResource("/gwentImages/img/sm/realms_siege_tower.jpg")),
    Realms_siegfried(CardInfo.SiegfriedOfDenesle,Card.class.getResource("/gwentImages/img/lg/realms_siegfried.jpg"), Card.class.getResource("/gwentImages/img/sm/realms_siegfried.jpg")),
    Realms_stennis(CardInfo.PrinceStennis,Card.class.getResource("/gwentImages/img/lg/realms_stennis.jpg"), Card.class.getResource("/gwentImages/img/sm/realms_stennis.jpg")),
    Realms_thaler(CardInfo.Thaler,Card.class.getResource("/gwentImages/img/lg/realms_thaler.jpg"), Card.class.getResource("/gwentImages/img/sm/realms_thaler.jpg")),
    Realms_trebuchet(CardInfo.Trebuchet,Card.class.getResource("/gwentImages/img/lg/realms_trebuchet.jpg"), Card.class.getResource("/gwentImages/img/sm/realms_trebuchet.jpg")),
    Realms_trebuchet_1(CardInfo.Trebuchet,Card.class.getResource("/gwentImages/img/lg/realms_trebuchet_1.jpg"), Card.class.getResource("/gwentImages/img/sm/realms_trebuchet_1.jpg")),
    Realms_vernon(CardInfo.VernonRoch,Card.class.getResource("/gwentImages/img/lg/realms_vernon.jpg"), Card.class.getResource("/gwentImages/img/sm/realms_vernon.jpg")),
    Realms_ves(CardInfo.Ves,Card.class.getResource("/gwentImages/img/lg/realms_ves.jpg"), Card.class.getResource("/gwentImages/img/sm/realms_ves.jpg")),
    Realms_yarpen(CardInfo.YarpenZirgrin,Card.class.getResource("/gwentImages/img/lg/realms_yarpen.jpg"), Card.class.getResource("/gwentImages/img/sm/realms_yarpen.jpg")),
    Scoiatael_barclay(CardInfo.BarclayEls,Card.class.getResource("/gwentImages/img/lg/scoiatael_barclay.jpg"), Card.class.getResource("/gwentImages/img/sm/scoiatael_barclay.jpg")),
    Scoiatael_ciaran(CardInfo.Ciaranaep,Card.class.getResource("/gwentImages/img/lg/scoiatael_ciaran.jpg"), Card.class.getResource("/gwentImages/img/sm/scoiatael_ciaran.jpg")),
    Scoiatael_dennis(CardInfo.DennisCranmer,Card.class.getResource("/gwentImages/img/lg/scoiatael_dennis.jpg"), Card.class.getResource("/gwentImages/img/sm/scoiatael_dennis.jpg")),
    Scoiatael_dol_archer(CardInfo.DolBlathannaArcher,Card.class.getResource("/gwentImages/img/lg/scoiatael_dol_archer.jpg"), Card.class.getResource("/gwentImages/img/sm/scoiatael_dol_archer.jpg")),
    Scoiatael_dol_infantry(CardInfo.DolBlathannaScout,Card.class.getResource("/gwentImages/img/lg/scoiatael_dol_infantry.jpg"), Card.class.getResource("/gwentImages/img/sm/scoiatael_dol_infantry.jpg")),
    Scoiatael_dol_infantry_1(CardInfo.DolBlathannaScout,Card.class.getResource("/gwentImages/img/lg/scoiatael_dol_infantry_1.jpg"), Card.class.getResource("/gwentImages/img/sm/scoiatael_dol_infantry_1.jpg")),
    Scoiatael_dol_infantry_2(CardInfo.DolBlathannaScout,Card.class.getResource("/gwentImages/img/lg/scoiatael_dol_infantry_2.jpg"), Card.class.getResource("/gwentImages/img/sm/scoiatael_dol_infantry_2.jpg")),
    Scoiatael_dwarf(CardInfo.DwarvenSkirmisher,Card.class.getResource("/gwentImages/img/lg/scoiatael_dwarf.jpg"), Card.class.getResource("/gwentImages/img/sm/scoiatael_dwarf.jpg")),
    Scoiatael_dwarf_1(CardInfo.DwarvenSkirmisher,Card.class.getResource("/gwentImages/img/lg/scoiatael_dwarf_1.jpg"), Card.class.getResource("/gwentImages/img/sm/scoiatael_dwarf_1.jpg")),
    Scoiatael_dwarf_2(CardInfo.DwarvenSkirmisher,Card.class.getResource("/gwentImages/img/lg/scoiatael_dwarf_2.jpg"), Card.class.getResource("/gwentImages/img/sm/scoiatael_dwarf_2.jpg")),
    Scoiatael_eithne(CardInfo.Eithne,Card.class.getResource("/gwentImages/img/lg/scoiatael_eithne.jpg"), Card.class.getResource("/gwentImages/img/sm/scoiatael_eithne.jpg")),
    Scoiatael_elf_skirmisher(CardInfo.ElvenSkirmisher,Card.class.getResource("/gwentImages/img/lg/scoiatael_elf_skirmisher.jpg"), Card.class.getResource("/gwentImages/img/sm/scoiatael_elf_skirmisher.jpg")),
    Scoiatael_elf_skirmisher_1(CardInfo.ElvenSkirmisher,Card.class.getResource("/gwentImages/img/lg/scoiatael_elf_skirmisher_1.jpg"), Card.class.getResource("/gwentImages/img/sm/scoiatael_elf_skirmisher_1.jpg")),
    Scoiatael_elf_skirmisher_2(CardInfo.ElvenSkirmisher,Card.class.getResource("/gwentImages/img/lg/scoiatael_elf_skirmisher_2.jpg"), Card.class.getResource("/gwentImages/img/sm/scoiatael_elf_skirmisher_2.jpg")),
    Scoiatael_filavandrel(CardInfo.Filavandrel,Card.class.getResource("/gwentImages/img/lg/scoiatael_filavandrel.jpg"), Card.class.getResource("/gwentImages/img/sm/scoiatael_filavandrel.jpg")),
    Scoiatael_francesca_bronze(CardInfo.PureBloodElf,Card.class.getResource("/gwentImages/img/lg/scoiatael_francesca_bronze.jpg"), Card.class.getResource("/gwentImages/img/sm/scoiatael_francesca_bronze.jpg")),
    Scoiatael_francesca_copper(CardInfo.DisplayOfTheValley,Card.class.getResource("/gwentImages/img/lg/scoiatael_francesca_copper.jpg"), Card.class.getResource("/gwentImages/img/sm/scoiatael_francesca_copper.jpg")),
    Scoiatael_francesca_gold(CardInfo.TheBeautiful,Card.class.getResource("/gwentImages/img/lg/scoiatael_francesca_gold.jpg"), Card.class.getResource("/gwentImages/img/sm/scoiatael_francesca_gold.jpg")),
    Scoiatael_francesca_hope_of_the_aen_seidhe(CardInfo.HopeOfTheAenSeidhe,Card.class.getResource("/gwentImages/img/lg/scoiatael_francesca_hope_of_the_aen_seidhe.jpg"), Card.class.getResource("/gwentImages/img/sm/scoiatael_francesca_hope_of_the_aen_seidhe.jpg")),
    Scoiatael_francesca_silver(CardInfo.QueenOfDolBlathanna,Card.class.getResource("/gwentImages/img/lg/scoiatael_francesca_silver.jpg"), Card.class.getResource("/gwentImages/img/sm/scoiatael_francesca_silver.jpg")),
    Scoiatael_havekar_nurse(CardInfo.HavekarHealer,Card.class.getResource("/gwentImages/img/lg/scoiatael_havekar_nurse.jpg"), Card.class.getResource("/gwentImages/img/sm/scoiatael_havekar_nurse.jpg")),
    Scoiatael_havekar_nurse_1(CardInfo.HavekarHealer,Card.class.getResource("/gwentImages/img/lg/scoiatael_havekar_nurse_1.jpg"), Card.class.getResource("/gwentImages/img/sm/scoiatael_havekar_nurse_1.jpg")),
    Scoiatael_havekar_nurse_2(CardInfo.HavekarHealer,Card.class.getResource("/gwentImages/img/lg/scoiatael_havekar_nurse_2.jpg"), Card.class.getResource("/gwentImages/img/sm/scoiatael_havekar_nurse_2.jpg")),
    Scoiatael_havekar_support(CardInfo.HavekarSmuggler,Card.class.getResource("/gwentImages/img/lg/scoiatael_havekar_support.jpg"), Card.class.getResource("/gwentImages/img/sm/scoiatael_havekar_support.jpg")),
    Scoiatael_havekar_support_1(CardInfo.HavekarSmuggler,Card.class.getResource("/gwentImages/img/lg/scoiatael_havekar_support_1.jpg"), Card.class.getResource("/gwentImages/img/sm/scoiatael_havekar_support_1.jpg")),
    Scoiatael_havekar_support_2(CardInfo.HavekarSmuggler,Card.class.getResource("/gwentImages/img/lg/scoiatael_havekar_support_2.jpg"), Card.class.getResource("/gwentImages/img/sm/scoiatael_havekar_support_2.jpg")),
    Scoiatael_ida(CardInfo.IdaEmeanaep,Card.class.getResource("/gwentImages/img/lg/scoiatael_ida.jpg"), Card.class.getResource("/gwentImages/img/sm/scoiatael_ida.jpg")),
    Scoiatael_iorveth(CardInfo.Iorveth,Card.class.getResource("/gwentImages/img/lg/scoiatael_iorveth.jpg"), Card.class.getResource("/gwentImages/img/sm/scoiatael_iorveth.jpg")),
    Scoiatael_isengrim(CardInfo.IsengrimFaoiltiarna,Card.class.getResource("/gwentImages/img/lg/scoiatael_isengrim.jpg"), Card.class.getResource("/gwentImages/img/sm/scoiatael_isengrim.jpg")),
    Scoiatael_mahakam(CardInfo.MahakamanDefender,Card.class.getResource("/gwentImages/img/lg/scoiatael_mahakam.jpg"), Card.class.getResource("/gwentImages/img/sm/scoiatael_mahakam.jpg")),
    Scoiatael_mahakam_1(CardInfo.MahakamanDefender,Card.class.getResource("/gwentImages/img/lg/scoiatael_mahakam_1.jpg"), Card.class.getResource("/gwentImages/img/sm/scoiatael_mahakam_1.jpg")),
    Scoiatael_mahakam_2(CardInfo.MahakamanDefender,Card.class.getResource("/gwentImages/img/lg/scoiatael_mahakam_2.jpg"), Card.class.getResource("/gwentImages/img/sm/scoiatael_mahakam_2.jpg")),
    Scoiatael_mahakam_3(CardInfo.MahakamanDefender,Card.class.getResource("/gwentImages/img/lg/scoiatael_mahakam_3.jpg"), Card.class.getResource("/gwentImages/img/sm/scoiatael_mahakam_3.jpg")),
    Scoiatael_mahakam_4(CardInfo.MahakamanDefender,Card.class.getResource("/gwentImages/img/lg/scoiatael_mahakam_4.jpg"), Card.class.getResource("/gwentImages/img/sm/scoiatael_mahakam_4.jpg")),
    Scoiatael_milva(CardInfo.Milva,Card.class.getResource("/gwentImages/img/lg/scoiatael_milva.jpg"), Card.class.getResource("/gwentImages/img/sm/scoiatael_milva.jpg")),
    Scoiatael_riordain(CardInfo.Riordain,Card.class.getResource("/gwentImages/img/lg/scoiatael_riordain.jpg"), Card.class.getResource("/gwentImages/img/sm/scoiatael_riordain.jpg")),
    Scoiatael_saskia(CardInfo.Seasenthessis,Card.class.getResource("/gwentImages/img/lg/scoiatael_saskia.jpg"), Card.class.getResource("/gwentImages/img/sm/scoiatael_saskia.jpg")),
    Scoiatael_schirru(CardInfo.Schirru,Card.class.getResource("/gwentImages/img/lg/scoiatael_schirru.jpg"), Card.class.getResource("/gwentImages/img/sm/scoiatael_schirru.jpg")),
    Scoiatael_toruviel(CardInfo.Toruviel,Card.class.getResource("/gwentImages/img/lg/scoiatael_toruviel.jpg"), Card.class.getResource("/gwentImages/img/sm/scoiatael_toruviel.jpg")),
    Scoiatael_vrihedd_brigade(CardInfo.VriheddBrigadeVeteran,Card.class.getResource("/gwentImages/img/lg/scoiatael_vrihedd_brigade.jpg"), Card.class.getResource("/gwentImages/img/sm/scoiatael_vrihedd_brigade.jpg")),
    Scoiatael_vrihedd_brigade_1(CardInfo.VriheddBrigadeVeteran,Card.class.getResource("/gwentImages/img/lg/scoiatael_vrihedd_brigade_1.jpg"), Card.class.getResource("/gwentImages/img/sm/scoiatael_vrihedd_brigade_1.jpg")),
    Scoiatael_vrihedd_cadet(CardInfo.VriheddBrigadeRecruit,Card.class.getResource("/gwentImages/img/lg/scoiatael_vrihedd_cadet.jpg"), Card.class.getResource("/gwentImages/img/sm/scoiatael_vrihedd_cadet.jpg")),
    Scoiatael_yaevinn(CardInfo.Yaevinn,Card.class.getResource("/gwentImages/img/lg/scoiatael_yaevinn.jpg"), Card.class.getResource("/gwentImages/img/sm/scoiatael_yaevinn.jpg")),
    Skellige_berserker(CardInfo.Berserker,Card.class.getResource("/gwentImages/img/lg/skellige_berserker.jpg"), Card.class.getResource("/gwentImages/img/sm/skellige_berserker.jpg")),
    Skellige_birna(CardInfo.BirnaBran,Card.class.getResource("/gwentImages/img/lg/skellige_birna.jpg"), Card.class.getResource("/gwentImages/img/sm/skellige_birna.jpg")),
    Skellige_blueboy(CardInfo.BlueboyLugos,Card.class.getResource("/gwentImages/img/lg/skellige_blueboy.jpg"), Card.class.getResource("/gwentImages/img/sm/skellige_blueboy.jpg")),
    Skellige_brokva_archer(CardInfo.ClanBrokvarArcher,Card.class.getResource("/gwentImages/img/lg/skellige_brokva_archer.jpg"), Card.class.getResource("/gwentImages/img/sm/skellige_brokva_archer.jpg")),
    Skellige_cerys(CardInfo.Cerys,Card.class.getResource("/gwentImages/img/lg/skellige_cerys.jpg"), Card.class.getResource("/gwentImages/img/sm/skellige_cerys.jpg")),
    Skellige_crach_an_craite(CardInfo.CrachAnCraite,Card.class.getResource("/gwentImages/img/lg/skellige_crach_an_craite.jpg"), Card.class.getResource("/gwentImages/img/sm/skellige_crach_an_craite.jpg")),
    Skellige_craite_warrior(CardInfo.ClanAnCraite,Card.class.getResource("/gwentImages/img/lg/skellige_craite_warrior.jpg"), Card.class.getResource("/gwentImages/img/sm/skellige_craite_warrior.jpg")),
    Skellige_dimun_pirate(CardInfo.ClanDimunPirate,Card.class.getResource("/gwentImages/img/lg/skellige_dimun_pirate.jpg"), Card.class.getResource("/gwentImages/img/sm/skellige_dimun_pirate.jpg")),
    Skellige_donar(CardInfo.DonaranHindar,Card.class.getResource("/gwentImages/img/lg/skellige_donar.jpg"), Card.class.getResource("/gwentImages/img/sm/skellige_donar.jpg")),
    Skellige_draig(CardInfo.DraigBonDhu,Card.class.getResource("/gwentImages/img/lg/skellige_draig.jpg"), Card.class.getResource("/gwentImages/img/sm/skellige_draig.jpg")),
    Skellige_ermion(CardInfo.Ermion,Card.class.getResource("/gwentImages/img/lg/skellige_ermion.jpg"), Card.class.getResource("/gwentImages/img/sm/skellige_ermion.jpg")),

    //    Skellige_hemdall(Card.class.getResource("/gwentImages/img/lg/skellige_hemdall.jpg")),

    //    Skellige_heymaey(Card.class.getResource("/gwentImages/img/lg/skellige_heymaey.jpg")),

    Skellige_hjalmar(CardInfo.Hjalmar,Card.class.getResource("/gwentImages/img/lg/skellige_hjalmar.jpg"), Card.class.getResource("/gwentImages/img/sm/skellige_hjalmar.jpg")),
    Skellige_holger(CardInfo.HolgerBlackhand,Card.class.getResource("/gwentImages/img/lg/skellige_holger.jpg"), Card.class.getResource("/gwentImages/img/sm/skellige_holger.jpg")),
    Skellige_kambi(CardInfo.Kambi,Card.class.getResource("/gwentImages/img/lg/skellige_kambi.jpg"), Card.class.getResource("/gwentImages/img/sm/skellige_kambi.jpg")),
    Skellige_king_bran(CardInfo.KingBran,Card.class.getResource("/gwentImages/img/lg/skellige_king_bran.jpg"), Card.class.getResource("/gwentImages/img/sm/skellige_king_bran.jpg")),
    Skellige_light_longship(CardInfo.LightLongship,Card.class.getResource("/gwentImages/img/lg/skellige_light_longship.jpg"), Card.class.getResource("/gwentImages/img/sm/skellige_light_longship.jpg")),
    Skellige_madmad_lugos(CardInfo.MadmanLugos,Card.class.getResource("/gwentImages/img/lg/skellige_madmad_lugos.jpg"), Card.class.getResource("/gwentImages/img/sm/skellige_madmad_lugos.jpg")),
    Skellige_olaf(CardInfo.Olaf,Card.class.getResource("/gwentImages/img/lg/skellige_olaf.jpg"), Card.class.getResource("/gwentImages/img/sm/skellige_olaf.jpg")),
    Skellige_shield_maiden(CardInfo.ClanDrummondShieldmaiden,Card.class.getResource("/gwentImages/img/lg/skellige_shield_maiden.jpg"), Card.class.getResource("/gwentImages/img/sm/skellige_shield_maiden.jpg")),
    Skellige_shield_maiden_1(CardInfo.ClanDrummondShieldmaiden,Card.class.getResource("/gwentImages/img/lg/skellige_shield_maiden_1.jpg"), Card.class.getResource("/gwentImages/img/sm/skellige_shield_maiden_1.jpg")),
    Skellige_shield_maiden_2(CardInfo.ClanDrummondShieldmaiden,Card.class.getResource("/gwentImages/img/lg/skellige_shield_maiden_2.jpg"), Card.class.getResource("/gwentImages/img/sm/skellige_shield_maiden_2.jpg")),
    Skellige_svanrige(CardInfo.Svanrige,Card.class.getResource("/gwentImages/img/lg/skellige_svanrige.jpg"), Card.class.getResource("/gwentImages/img/sm/skellige_svanrige.jpg")),
    Skellige_tordarroch(CardInfo.ClanTordarrochArmorsmith,Card.class.getResource("/gwentImages/img/lg/skellige_tordarroch.jpg"), Card.class.getResource("/gwentImages/img/sm/skellige_tordarroch.jpg")),
    Skellige_udalryk(CardInfo.Udalryk,Card.class.getResource("/gwentImages/img/lg/skellige_udalryk.jpg"), Card.class.getResource("/gwentImages/img/sm/skellige_udalryk.jpg")),
    Skellige_vildkaarl(CardInfo.Vidkaarl,Card.class.getResource("/gwentImages/img/lg/skellige_vildkaarl.jpg"), Card.class.getResource("/gwentImages/img/sm/skellige_vildkaarl.jpg")),
    Skellige_war_longship(CardInfo.WarLongship,Card.class.getResource("/gwentImages/img/lg/skellige_war_longship.jpg"), Card.class.getResource("/gwentImages/img/sm/skellige_war_longship.jpg")),
    Skellige_young_berserker(CardInfo.YoungBerserker,Card.class.getResource("/gwentImages/img/lg/skellige_young_berserker.jpg"), Card.class.getResource("/gwentImages/img/sm/skellige_young_berserker.jpg")),
    Skellige_young_vildkaarl(CardInfo.YoungVidkaarl,Card.class.getResource("/gwentImages/img/lg/skellige_young_vildkaarl.jpg"), Card.class.getResource("/gwentImages/img/sm/skellige_young_vildkaarl.jpg")),
    Special_decoy(CardInfo.Decoy,Card.class.getResource("/gwentImages/img/lg/special_decoy.jpg"), Card.class.getResource("/gwentImages/img/sm/special_decoy.jpg")),
    Special_horn(CardInfo.CommandersHorn,Card.class.getResource("/gwentImages/img/lg/special_horn.jpg"), Card.class.getResource("/gwentImages/img/sm/special_horn.jpg")),
    Special_mardroeme(CardInfo.Mardoeme,Card.class.getResource("/gwentImages/img/lg/special_mardroeme.jpg"), Card.class.getResource("/gwentImages/img/sm/special_mardroeme.jpg")),
    Special_scorch(CardInfo.Scorch,Card.class.getResource("/gwentImages/img/lg/special_scorch.jpg"), Card.class.getResource("/gwentImages/img/sm/special_scorch.jpg")),
    Weather_clear(CardInfo.ClearWeather,Card.class.getResource("/gwentImages/img/lg/weather_clear.jpg"), Card.class.getResource("/gwentImages/img/sm/weather_clear.jpg")),
    Weather_fog(CardInfo.ImpenetrableFog,Card.class.getResource("/gwentImages/img/lg/weather_fog.jpg"), Card.class.getResource("/gwentImages/img/sm/weather_fog.jpg")),
    Weather_frost(CardInfo.BitingFrost,Card.class.getResource("/gwentImages/img/lg/weather_frost.jpg"), Card.class.getResource("/gwentImages/img/sm/weather_frost.jpg")),
    Weather_rain(CardInfo.TorrentialRain,Card.class.getResource("/gwentImages/img/lg/weather_rain.jpg"), Card.class.getResource("/gwentImages/img/sm/weather_rain.jpg")),
    Weather_storm(CardInfo.SkelligeStorm,Card.class.getResource("/gwentImages/img/lg/weather_storm.jpg"), Card.class.getResource("/gwentImages/img/sm/weather_storm.jpg")),

    ;
    CardInfo card;
    URL path;
    URL path2;
    Path(CardInfo card, URL path,URL path2){

        this.path = path;
        this.path2 = path2;
        this.card = card;
    }

    public CardInfo getCard() {
        return card;
    }

    public URL getPath() {
        return path;
    }
    public URL getPath2() {
        return path2;
    }
    //    Path(String path){
//        this.path = path;
//        this.card = null;
//    }
}
